# Generated by Django 5.0.3 on 2024-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_item_images')),
                ('title', models.CharField(max_length=200)),
                ('title_desc', models.TextField()),
                ('ourstory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='servicesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_item_images')),
                ('title', models.CharField(max_length=200)),
                ('title_desc', models.TextField()),
            ],
        ),
    ]
