# Generated by Django 5.0.3 on 2024-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_servicesitem_desc_remove_servicesitem_title_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_from',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback_from',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback_from',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback_from',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
