# Generated by Django 5.0.3 on 2024-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_feedback_from_email_feedback_from_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutitems',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='servicesitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
