# Generated by Django 5.0.3 on 2024-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_aboutitems_image_alter_servicesitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutitems',
            name='image',
            field=models.ImageField(upload_to='about_item_images/'),
        ),
        migrations.AlterField(
            model_name='servicesitem',
            name='image',
            field=models.ImageField(upload_to='about_item_images/'),
        ),
    ]
