# Generated by Django 5.0.3 on 2024-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_rename_image_aboutitems_allimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutitems',
            name='allimage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='servicesitem',
            name='allimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
