# Generated by Django 5.0.3 on 2024-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_alter_aboutitems_allimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesItem_desc',
        ),
        migrations.AddField(
            model_name='servicesitem',
            name='title_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
