# Generated by Django 5.0.3 on 2024-03-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_delete_servicesitem_desc_servicesitem_title_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesItem_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesitem',
            name='title_desc',
        ),
    ]
